---
- name: Disk usage analysis for Windows servers 
  hosts: windows

  vars_files:
    - [ "secrets.yml" ]

  tasks:
    - name: Create configuration file
      template:
        src: templates/diskusage_config.j2
        dest: /tmp/diskusage_config.yaml
      check_mode: no
      register: diskusage_configfile_creation
      when: diskusage_customfile == 't'                   # using a flag to control if we want to execute it or not.
      notify: diskusage_configfile_creation
      delegate_to: localhost                              # to change context to local instead of remote.

    - name: Copy diskusage config file to target host     # this task is execute when the previous one was done as well
      win_copy:
        src: /tmp/diskusage_config.yaml
        dest: "{{ ansible_user_dir }}\\"
      when: diskusage_configfile_creation.changed

    - name: Copy diskusage binary
      win_copy:
        src: files/diskusage.exe
        dest: "{{ ansible_user_dir }}\\"
    
    - name: Generate disk usage report
      win_command: "{{ ansible_user_dir }}\\diskusage.exe"
      register: diskusage_execution    

    - name: Get disk usage report
      fetch:
        src: C:\users\vagrant\diskusage_out.txt
        dest: ./files/diskusage_out_{{ ansible_hostname }}_{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}.txt
        flat: yes
      when: diskusage_execution is success
      register: report_result
      notify: 
        #- diskusage_report_slack
        - diskusage_report_email

    # - debug:
    #     msg: "{{ gmail_passwd }}"

  handlers:     
    - name: diskusage_report_slack
      slack:
        token: '{{ slack_token }}'
        msg: '2do reto completado!'
      delegate_to: localhost

    - name: diskusage_report_email
      mail:
        host: smtp.gmail.com
        port: 587
        username: 'karkul@gmail.com'
        password: '{{ gmail_passwd }}'
        to: '{{ mail_to }}'
        subject: Ansible-report | Disk Usage | {{ ansible_hostname }}
        body: This is the disk usage of the system {{ ansible_hostname }}
        attach:
          - "{{ report_result.dest }}"
      delegate_to: localhost
