# Playbook de demo para setear un web server
---

- name: Apache server setup
  hosts: web
  become: yes
  become_method: sudo
  
  tasks:
    - name: Adding user
      command: useradd developer

    - name: Install Apache
      yum:
        name: "httpd"
        state: present
        update_cache: yes
    
    - name: Start Apache
      service:
        name: "httpd"
        state: started

