# Playbook de demo para setear un web server
---

- name: Apache server setup
  hosts: web
  become: yes
  become_method: sudo
  
  tasks:
    - name: Adding user
      user:
        name: developer
        group: wheel
        shell: /bin/bash          
      register: user_result

    - name: Install Apache
      yum:
        name: "httpd"
        state: present
        update_cache: yes
    
    - name: Start Apache
      service:
        name: "httpd"
        state: started
      notify: service_started
  
  handlers:
    - name: service_started
      slack:
        token: T021GFM66TV/B023VRWH4PN/5k5Vxw3QyH8EyS77EohfeEG1
        msg: 'testing handlers'
      delegate_to: localhost

